List<Map<String, dynamic>> appliances = [
  {"applianceName": "Air conditioner (<1 Ton)", "powerConsumed": 1000},
  {"applianceName": "Air conditioner (1-2 Ton)", "powerConsumed": 2300},
  {"applianceName": "Air conditioner (>2 Ton)", "powerConsumed": 3200},
  {"applianceName": "Air cooler portable", "powerConsumed": 150},
  {"applianceName": "Air cooler fixed", "powerConsumed": 600},
  {"applianceName": "Coffee percolator", "powerConsumed": 600},
  {"applianceName": "Computer", "powerConsumed": 300},
  {"applianceName": "Laptop", "powerConsumed": 50},
  {"applianceName": "Deep fryer", "powerConsumed": 1800},
  {"applianceName": "Dishwasher", "powerConsumed": 2400},
  {
    "applianceName": "Domestic water pressure pump (<1kW)",
    "powerConsumed": 750
  },
  {
    "applianceName": "Domestic water pressure pump (>1kW)",
    "powerConsumed": 1125
  },
  {"applianceName": "Fan (Exhaust)", "powerConsumed": 40},
  {"applianceName": "Fan (Ceiling)", "powerConsumed": 100},
  {"applianceName": "Griller(<1kW)", "powerConsumed": 660},
  {"applianceName": "Griller Large", "powerConsumed": 2400},
  {"applianceName": "Hair dryer", "powerConsumed": 1000},
  {"applianceName": "Iron", "powerConsumed": 600},
  {"applianceName": "Ironing machine", "powerConsumed": 1000},
  {"applianceName": "Juice extractor", "powerConsumed": 300},
  {"applianceName": "Kettle", "powerConsumed": 1800},
  {"applianceName": "Small Lighting CFL", "powerConsumed": 7},
  {"applianceName": "Lighting CFL", "powerConsumed": 16},
  {"applianceName": "Lighting incandescent (<40W)", "powerConsumed": 25},
  {"applianceName": "Lighting incandescent (60W)", "powerConsumed": 60},
  {"applianceName": "Lighting incandescent (100W)", "powerConsumed": 100},
  {"applianceName": "Small Lighting LED", "powerConsumed": 6},
  {"applianceName": "Lighting LED", "powerConsumed": 15},
  {"applianceName": "Microoven Convection", "powerConsumed": 1600},
  {"applianceName": "Radio", "powerConsumed": 60},
  {"applianceName": "Refrigerator (250L)", "powerConsumed": 210},
  {"applianceName": "Refrigerator (500L)", "powerConsumed": 260},
  {"applianceName": "Refrigerator (600L)", "powerConsumed": 400},
  {"applianceName": "Television LCD", "powerConsumed": 200},
  {"applianceName": "Television LED", "powerConsumed": 450},
  {"applianceName": "Toaster (Plain)", "powerConsumed": 600},
  {"applianceName": "Toaster (Auto)", "powerConsumed": 1200},
  {"applianceName": "Vacuum cleaner", "powerConsumed": 1100},
  {"applianceName": "Washing machine (Semi Auto)", "powerConsumed": 500},
  {"applianceName": "Washing machine (Auto)", "powerConsumed": 900},
  {"applianceName": "Phone", "powerConsumed": 299},
];
