// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdVG57t2f9jXkL5yBfAziUIgOSb9tA1D8',
    appId: '1:446449876620:web:a2080fd235ef451ba205a9',
    messagingSenderId: '446449876620',
    projectId: 'ecostride-333d8',
    authDomain: 'ecostride-333d8.firebaseapp.com',
    storageBucket: 'ecostride-333d8.appspot.com',
    measurementId: 'G-WJ954HBP94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIpBF_-qq1sfSuR3I7L17cs0dipypK0b4',
    appId: '1:446449876620:android:a4744ec70976614aa205a9',
    messagingSenderId: '446449876620',
    projectId: 'ecostride-333d8',
    storageBucket: 'ecostride-333d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWUtHySOCqNO1TZjJTJ99hskMeijI-Y6g',
    appId: '1:446449876620:ios:d03fda372e47f346a205a9',
    messagingSenderId: '446449876620',
    projectId: 'ecostride-333d8',
    storageBucket: 'ecostride-333d8.appspot.com',
    iosBundleId: 'com.example.ecostrider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWUtHySOCqNO1TZjJTJ99hskMeijI-Y6g',
    appId: '1:446449876620:ios:4099611787e76a5aa205a9',
    messagingSenderId: '446449876620',
    projectId: 'ecostride-333d8',
    storageBucket: 'ecostride-333d8.appspot.com',
    iosBundleId: 'com.example.ecostrider.RunnerTests',
  );
}
